services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    # pull_policy: always
    tty: true
    restart: on-failure
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - 11434:11434
    networks:
      - ollama-network
    #environment:
    #- 'OLLAMA_KEEP_ALIVE=-1m'

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      # - ${OPEN_WEBUI_PORT-3000}:8080
      - 8080:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'WEBUI_AUTH=false'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: on-failure
    networks:
      - ollama-network

volumes:
  ollama:
    name: ollama
  open-webui:
    name: open-webui

networks:
  ollama-network:
    name: ollama-network
