services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: on-failure
    tty: true
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    networks:
      - ollama-network
    environment:
      - OLLAMA_CONTEXT_LENGTH=8192

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: on-failure
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
      - 'WEBUI_AUTH=false'
      # - 'HF_HUB_OFFLINE=1'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama-network

volumes:
  ollama:
    name: ollama
  open-webui:
    name: open-webui

networks:
  ollama-network:
    name: ollama-network
